controller:
  replicaCount: 1
  persistence:
    enabled: false

broker:
  replicaCount: 0

kraft:
  enabled: true

zookeeper:
  enabled: false

listeners:
  client:
    protocol: PLAINTEXT

provisioning:
  enabled: false
