replicaCount: 1

persistence:
  enabled: false

kraft:
  enabled: true

zookeeper:
  enabled: false

listeners:
  client:
    protocol: PLAINTEXT

provisioning:
  enabled: true
  topics:
    - name: payment.created
      partitions: 3
      replicationFactor: 1
    - name: payment.approved
      partitions: 3
      replicationFactor: 1
    - name: payment.flagged
      partitions: 3
      replicationFactor: 1
