apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://__RDS_ENDPOINT__:5432/payments"
  SPRING_DATASOURCE_USERNAME: "__DB_USERNAME__"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "__KAFKA_BOOTSTRAP_SERVERS__"
  RAZORPAY_ENABLED: "__RAZORPAY_ENABLED__"
  RAZORPAY_MERCHANT_NAME: "__RAZORPAY_MERCHANT_NAME__"
  RAZORPAY_DESCRIPTION: "__RAZORPAY_DESCRIPTION__"
  RAZORPAY_RECEIVER_NAME: "__RAZORPAY_RECEIVER_NAME__"
