apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "__DB_PASSWORD__"
  RAZORPAY_KEY_ID: "__RAZORPAY_KEY_ID__"
  RAZORPAY_KEY_SECRET: "__RAZORPAY_KEY_SECRET__"
