apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-service
  labels:
    app: fraud-detection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-service
  template:
    metadata:
      labels:
        app: fraud-detection-service
    spec:
      containers:
        - name: fraud-detection-service
          image: __ECR_REGISTRY__/payments-sim/fraud-detection-service:__IMAGE_TAG__
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 15
